### ISSUE TITLE
Scale factor in toVoltage function

### ISSUE THREAD

**Issue by vanniaz** [pilotak/MCP3021#5]
The **toVoltage** functions divide by 1023 for MCP3021 and 4095 for MCP3221, but the correct values are 1024 and 4096.
It is true that the full-scale voltage corresponds to 1023 and 4095, but the range is still 1024 and 4096 steps (2^N).
This is also indicated in the datasheet:
![image](https://user-images.githubusercontent.com/29131569/123235274-01060f00-d4dc-11eb-86b7-33539a536559.png)
If you divide by 1023 and 4095 your digital values will not be centered on the corresponding voltage values but they will vary across the range. The only downside of dividing by 2^N is that **toVoltage** will never reach the full Vref value, e.g. with 3.3V on the MCP3021 you will get 3.297V, but this is correct because the converter will output 1023 for any analog voltage above 3.295V.

This is well explained by this picture (source: [https://www.embedded.com/understanding-analog-to-digital-converter-specifications/](url)
![image](https://user-images.githubusercontent.com/29131569/123240424-97d4ca80-d4e0-11eb-8282-cbd510341d29.png)

**Comment by pilotak** [comment]
yes you are corrent, i found this bug in my other code but forgot this should be fixed in this lib too. Do you want to submit a PR?

**Comment by vanniaz** [comment]
OK I am not sure how to do it but I will try J

**Comment by vanniaz** [comment]
I submitted a pull request.
Not sure whether I did it correctly, never did it before!

**Comment by pilotak** [comment]
looks good, a good practice is not to close an issue manually but if you reference it, it will get closed automatically when merged https://bloggie.io/@kinopyo/github-tip-closing-issue-automatically-when-the-pull-request-is-merged

**Comment by vanniaz** [comment]
I did not know that, I will follow your advice next time.

This was an easy modification since I changed just a few characters in the source code, not exactly a major improvement. However it was the chance for me to try the fork/pull request mechanism.

Thank you!
